services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "pg_password"
      POSTGRES_DB: "kanastra"
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672

  app:
    build: .
    container_name: 'app'
    environment:
      DATABASE_URL: postgresql+psycopg2://root:pg_password@postgres/kanastra
      HOST_RABBITMQ: rabbitmq
    ports:
      - 8080:8080