services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "pg_password"
      POSTGRES_DB: "kanastra"
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672

  app:
    build: .
    entrypoint: "poetry run uvicorn app.main:app --host 0.0.0.0 --port 8080"
    container_name: "app"
    environment:
      DATABASE_URL: postgresql+psycopg2://root:pg_password@postgres/kanastra
      HOST_RABBITMQ: rabbitmq
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - rabbitmq

  worker:
    build: .
    entrypoint: "poetry run python run_worker.py"
    environment:
      DATABASE_URL: postgresql+psycopg2://root:pg_password@postgres/kanastra
      HOST_RABBITMQ: rabbitmq
    depends_on:
      - postgres
      - rabbitmq
    deploy:
      mode: replicated
      replicas: 2
